steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'us-central1-docker.pkg.dev/eighth-vehicle-375706/cloud-sql-fastapi/test:latest']
# Build the container image

- name: 'gcr.io/kaniko-project/executor:latest'
    args:
    - --cache=true
    - --cache-ttl=6h
    - --destination=us-central1-docker.pkg.dev/eighth-vehicle-375706/cloud-sql-fastapi/test:$COMMIT_SHA
    
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/eighth-vehicle-375706/cloud-sql-fastapi/test:$COMMIT_SHA']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  secretEnv:
    - "DB_NAME"
    - "DB_PASS"
    - "DB_USER"
    - "GOOGLE_APPLICATION_CREDENTIALS"
    - "INSTANCE_CONNECTION_NAME"
  args:
  - -c
  - |
    gcloud run deploy cloud-sql-fastapi \
    --image us-central1-docker.pkg.dev/eighth-vehicle-375706/cloud-sql-fastapi/test:$COMMIT_SHA \
    --region us-central1 \
    --allow-unauthenticated \
    --update-secrets=DB_NAME=DB_NAME:latest \
    --update-secrets=DB_USER=DB_USER:latest \
    --update-secrets=DB_PASS=DB_PASS:latest \
    --update-secrets=GOOGLE_APPLICATION_CREDENTIALS=GOOGLE_APPLICATION_CREDENTIALS:latest \
    --update-secrets=INSTANCE_CONNECTION_NAME=INSTANCE_CONNECTION_NAME:latest
  #- 'run'
  #- 'deploy'
  #- 'cloud-sql-fastapi'
  #- '--image'
  #- 'us-central1-docker.pkg.dev/eighth-vehicle-375706/cloud-sql-fastapi/test:$COMMIT_SHA'
  #- '--region'
  #- 'us-central1'
  #- '--allow-unauthenticated'
availableSecrets:
  secretManager:
  - versionName: projects/871578364011/secrets/DB_NAME/versions/1
    env: DB_NAME
  - versionName: projects/871578364011/secrets/DB_PASS/versions/1
    env: DB_PASS
  - versionName: projects/871578364011/secrets/DB_USER/versions/1
    env: DB_USER
  - versionName: projects/871578364011/secrets/GOOGLE_APPLICATION_CREDENTIALS/versions/1
    env: GOOGLE_APPLICATION_CREDENTIALS 
  - versionName: projects/871578364011/secrets/INSTANCE_CONNECTION_NAME/versions/1
    env: INSTANCE_CONNECTION_NAME 
images:
- 'us-central1-docker.pkg.dev/eighth-vehicle-375706/cloud-sql-fastapi/test:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY